[tool.poetry]
name = "conda_vulnerability_scanner"
version = "0.1.0"
description = "Tool to scan for vulnerabilities in a conda environment "
authors = ["Exasol AG <opensource@exasol.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
nox = "^2022.8.7"
exasol-sphinx-github-pages-generator = { git = "https://github.com/exasol/sphinx-github-pages-generator.git", tag = "0.1.0"}
gitpython = ">=2.1.0"
toml = ">=0.10.2"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
